apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app-with-argocd-hooks
  namespace: argocd
spec:
  destination:
    namespace: helm-app
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: helm-app-with-argocd-hooks
    repoURL: "https://github.com/lukaszjozwiak/argocd-helm-k8s.git"
    targetRevision: main
    helm:
      releaseName: helm-app-with-argocd-hooks
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
