apiVersion: batch/v1
kind: Job
metadata:
  name: counter
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: counter
          image: busybox
          command: [ "sh", "-c", "for i in $(seq 1 10); do echo $i; sleep 1; done" ]
      restartPolicy: Never
  backoffLimit: 4
